# Giai đoạn Build (Builder Stage)
FROM node:20-alpine AS builder

WORKDIR /app

COPY package.json yarn.lock* package-lock.json* ./

RUN \
  if [ -f "yarn.lock" ]; then yarn install --frozen-lockfile; \
  elif [ -f "package-lock.json" ]; then npm ci; \
  else npm install; fi

COPY . .

RUN npm run build

# Giai đoạn Production (Production Stage)
FROM node:20-alpine AS production

WORKDIR /app

# Copy only necessary files from builder stage
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/dist ./dist
COPY package.json ./

# Expose the port your NestJS app listens on
EXPOSE 4002

# Command to run your NestJS application
CMD ["node", "dist/main"]